# Generated by Django 2.1.7 on 2019-03-27 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('address', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('features', models.CharField(max_length=50)),
                ('ratings', models.IntegerField(default=0)),
                ('number_of_ratings', models.IntegerField(default=0)),
                ('reviews', models.CharField(max_length=20000)),
                ('realtor_agent', models.CharField(max_length=200)),
                ('realtor_site', models.CharField(default='google.com', max_length=200)),
                ('phone_number', models.CharField(default='999-999-9999', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
