# Generated by Django 2.1.7 on 2019-03-27 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='features',
            field=models.CharField(default='[]', max_length=50),
        ),
        migrations.AlterField(
            model_name='listing',
            name='reviews',
            field=models.CharField(default='[]', max_length=20000),
        ),
    ]
