# Generated by Django 2.1.7 on 2019-03-27 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190327_0418'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='baths',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listing',
            name='beds',
            field=models.IntegerField(default=0),
        ),
    ]
