# Generated by Django 2.1.7 on 2019-04-08 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190327_0458'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='back_View',
            field=models.ImageField(default='static/images/rotunda', upload_to='media', verbose_name='Back View'),
        ),
        migrations.AddField(
            model_name='listing',
            name='front_View',
            field=models.ImageField(default='static/images/rotunda', upload_to='media'),
        ),
        migrations.AddField(
            model_name='listing',
            name='interior_View',
            field=models.ImageField(default='static/images/rotunda', upload_to='media', verbose_name='Interior View'),
        ),
    ]
