# Generated by Django 2.1.4 on 2019-04-22 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20190422_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='back_View',
            field=models.ImageField(default='rotunda.jpg', upload_to='back', verbose_name='Back View'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='front_View',
            field=models.ImageField(default='rotunda.jpg', upload_to='front'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='interior_View',
            field=models.ImageField(default='rotunda.jpg', upload_to='interior', verbose_name='Interior View'),
        ),
    ]
