# Generated by Django 2.1.4 on 2019-04-28 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20190422_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='front_View',
            field=models.ImageField(default="{% static 'images/vsabre.jpg'%}", upload_to='front'),
        ),
    ]
