# Generated by Django 2.1.4 on 2019-04-28 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20190428_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='back_View',
            field=models.ImageField(default='static/images/vsabre.jpg', upload_to='media', verbose_name='Back View'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='front_View',
            field=models.ImageField(default='static/images/vsabre.jpg', upload_to='media'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='interior_View',
            field=models.ImageField(default='static/images/vsabre.jpg', upload_to='media', verbose_name='Interior View'),
        ),
    ]
