# Generated by Django 2.1.4 on 2019-04-29 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20190428_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='total_ratings',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='listing',
            name='realtor_site',
            field=models.CharField(max_length=200),
        ),
    ]
